# Конспект по ютуб видео (https://www.youtube.com/watch?v=kPxASj5wJBY)

## **Popularity based recommendatioanl system**

системы, которые предлагают пользователю продукты или услуги, которые наиболее популярны на местном или всемирном рынке на данной платформе

- Использует товары или услуги, которые популярны сейчас (в тренде)
- Ранжирует предметы основываясь на пользовательских рейтингах, истории продукта, кол-ву просмотров и так далее

In [1]:
import pandas as pd
import numpy as np

Загружаю датасет с фильмами

In [2]:
movies = pd.read_csv('movies.csv')
print(f'Колонки датасета: {movies.columns.tolist()}')
movies.head(3)

Колонки датасета: ['movieId', 'title', 'genres']

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance

Загружаю датасет с рейтингом

In [3]:
ratings = pd.read_csv('ratings.csv')
print(f'Колонки датасета: {ratings.columns.tolist()}')
ratings.head(3)

Колонки датасета: ['userId', 'movieId', 'rating', 'timestamp']

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182

Кол-во разных пользователей в датасете:

In [4]:
print(f'Кол-во разных пользователей в датасете: {len(ratings["userId"].value_counts().index.tolist())}')

Кол-во разных пользователей в датасете: 671

Объединяем два датасета по колонке с ID фильма

In [8]:
movie_data = pd.merge(ratings, movies, on='movieId')
movie_data.head()

,userId,movieId,rating,timestamp,title,genres
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama
1,1,1029,3.0,1260759179,Dumbo (1941),Animation|Children|Drama|Musical
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller
3,1,1129,2.0,1260759185,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller
4,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama

Теперь, надо определить **параметры для Popularity Based Recomendational System**

Такими критериями *(параметрами)* будут:
- Фильмы с наибольшим рейтингом
- Кол-во просмотров

Средний рейтинг фильмов:

In [12]:
average_rate = movie_data['rating'].mean()
print(f'Средний рейтинг: {float(average_rate):.2f}')

Средний рейтинг: 3.54

Получаю средний рейтинг **для каждого фильма**

In [16]:
ag_ratings = movie_data.groupby('title')['rating'].mean()
ag_ratings.head()

title
"Great Performances" Cats (1998)           1.750000
$9.99 (2008)                               3.833333
'Hellboy': The Seeds of Creation (2004)    2.000000
'Neath the Arizona Skies (1934)            0.500000
'Round Midnight (1986)                     2.250000
Name: rating, dtype: float64

In [24]:
ag_ratings.sort_values(ascending=False).head(10)

title
Zerophilia (2005)                                                              5.0
'night Mother (1986)                                                           5.0
Zelary (2003)                                                                  5.0
Dorian Blues (2004)                                                            5.0
Disappearance of Haruhi Suzumiya, The (Suzumiya Haruhi no shôshitsu) (2010)    5.0
Two Ninas (1999)                                                               5.0
Seve (2014)                                                                    5.0
Dr. Jekyll and Mr. Hyde (1941)                                                 5.0
Two Escobars, The (2010)                                                       5.0
Drained (O cheiro do Ralo) (2006)                                              5.0
Name: rating, dtype: float64